version: '3'
services:
  mongo6:
    image: mongo:${MONGO6_VERSION}
    container_name: mongo6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO6_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO6_ROOT_PASSWORD}
    volumes:
      - ${MONGO6_DIR}/data:/data/db:rw
    ports:
      - ${MONGO6_PORT}:27017
    restart: ${MONGO6_RESTART_POLICY}
    networks:
      - dev

networks:
  dev:
    external: true
